### PR TITLE
Validate clap

### LINKED ISSUE #91: Can clap's configuration be asserted statically?
In #90 we didn't discover that there was an issue until runtime. Given that this always panics, it would be nice to figure out if there is a way to either:

1. get a compile-time failure
2. assert the failure after construction so that every command fails if something is wrong

### PR DESCRIPTION
**Pull request by steveklabnik**
~~This will eventually fix #91, but it's going to be failing until I work through all of the current failures.~~

This introduces a test that will assert that the state built up within
clap is coherent.

Fixes https://github.com/oxidecomputer/humility/issues/91

Most of these removals or changes are simply fixes, but we also change
`jefe -h` to `jefe -H`

Fixes https://github.com/oxidecomputer/humility/issues/90

### CODE REVIEW

**Comment by steveklabnik** [comment]
I don't understand this latest failure because it's right there: https://github.com/oxidecomputer/humility/blob/master/cmd/spi/src/lib.rs#L57

**Comment by steveklabnik** [comment]
Thanks to clap's `debug` feature:

```
[clap::build::arg::debug_asserts]       Arg::_debug_asserts:bigendian-address
```

you give the name of the flag (`bigendian-address`) not the name of the struct member (`bigendian_address`). nice.

**Review by bcantrill — APPROVED** [review]
This looks great -- sorry about the delay!

**Comment by steveklabnik** [comment]
To be honest I thought it was already merged, that's my bad!

**Pull request merged**
