### PR TITLE
Add basic GitHub Action

### PR DESCRIPTION
**Pull request by steveklabnik**
This is a very basic Actions setup. I figure we can start here and iterate.

Latest questions here: https://github.com/oxidecomputer/humility/pull/51#issuecomment-989212627

~~@bcantrill some comments/thoughts:~~

~~* I left in a `cargo test` because even though we don't have any tests, nice to have it there for when we do. If you don't plan on any testing any time soon, could remove it.~~
~~* rustfmt uses nightly options here, I don't know if you want to pin to a nightly or just use "nightly" generally.~~
~~* speaking of which it seems like humility is currently not rustfmt clean, happy to push a commit here that fixes that, but i wonder if it's a nightly divergence~~
~~* this version thing also goes for the main build; i just left it on "stable" but if you want something other than that, happy to tweak.~~
~~* I left a clippy action in here too just for kicks, if you don't want this, happy to remove~~

~~This does *not* currently include the license check from Hubris. Extracting that from hubris's build system will take some more work. Happy to do that as part of this PR or as a follow-up.~~

### CODE REVIEW

**Comment by steveklabnik** [comment]
* rustfmt is failing on pmbus and spd
* I want to add some more sophisticated build caching but until we answer the above questions, wanted to keep it simple and easy to review.

**Comment by steveklabnik** [comment]
A toolchain file is being added in https://github.com/oxidecomputer/humility/pull/54

**Comment by steveklabnik** [comment]
https://github.com/oxidecomputer/humility/pull/56 moves the submodules to git deps, which means we *should* be rustfmt clean after that is merged.

**Comment by steveklabnik** [comment]
I have pushed a commit that gets clippy clean. I am not saying that you *should* enforce clippy in CI, or take that patch, but I figured that having access to that would make said decision easier or harder. I do think there's at least one bit of this that you should take regardless, and that's https://github.com/oxidecomputer/humility/pull/51/commits/1075ae73274973c493d65fc22c55351112cbb764#diff-6c2cd2ddc6195c23d24ae83f43a64f5822500f7fcac1c17cef6f82e4b3c7dd12L473-R473, this is a real bug. The rest is, I think overall good but also neutral and it's really up to you. I also made some small judgement calls in how to handle some of them; I bet that the string format literal stuff was on purpose and so I tried to suppress the warning rather than "fix" it the way clippy may have wanted to.

**Comment by steveklabnik** [comment]
Okay, this is green! Some final decisions before I merge:

- [ ] Do we want to bother with `cargo test`?
- [ ] Formatting is using the `nightlly` toolchain, is that okay or do you want a specific nightly?
- [ ] Do you want clippy and the associated commit, or not?
- [ ] Do you want license checking in here or not? I think it should exist but it's more work and I'd like to land this first, but if you feel differently I am open to it.

I want to add some more sophisticated build caching but until we answer the above questions, wanted to keep it simple and easy to review.

**Comment by bcantrill** [comment]
> Okay, this is green! Some final decisions before I merge:
> 
> * [ ]  Do we want to bother with `cargo test`?
> * [ ]  Formatting is using the `nightly` toolchain, is that okay or do you want a specific nightly?
> * [ ]  Do you want clippy and the associated commit, or not?
> * [ ]  Do you want license checking in here or not? I think it should exist but it's more work and I'd like to land this first, but if you feel differently I am open to it.
> 
> I want to add some more sophisticated build caching but until we answer the above questions, wanted to keep it simple and easy to review.

Yes on `cargo test`; `nightly` is good for rustfmt; yes on `cliippy`; license checking up to you, but agreed about landing this first! Thanks for doing this!

**Comment by steveklabnik** [comment]
Filed https://github.com/oxidecomputer/humility/issues/58 to track the licensing thing. This is now good to go! Merging!

**Pull request merged**
